# Dependencies
markdown:            redcarpet
# highlighter:         pygments

# Permalinks
#
permalink:           pretty 

gems:
  - jekyll-sitemap

# Setup
title:               BccSafe's Blog
tagline:             'Fight for a future'
description:         '这里有一个年轻的互联网人，做着一点自己觉得很酷的事情 <a href="mailto:bccsafe5988@gmail.com" target="_blank">@BccSafe</a>'
url:                 http://www.bccsafe.com
baseurl:             /
paginate:            8

# About/contact
author:
  name:              BccSafe 
  url:               https://www.bccsafe.com 
  email:             bccsafe5988@gmail.com 

# Custom vars
version:             1.0.0
