# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               BccSafe's Blog
tagline:             '为了遇见更好的自己'
description:         '这里有一个年轻的互联网人，做着一点自己觉得很酷的事情 <a href="mailto:bccsafe5988@gmail.com" target="_blank">@BccSafe</a>'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              BccSafe 
  url:               https://www.baidu.com 
  email:             bccsafe5988@gmail.com 

# Custom vars
version:             1.0.0
